# Generated by Django 5.0.3 on 2024-04-08 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_livre', models.IntegerField()),
                ('Titre_livre', models.CharField(max_length=50)),
                ('Nbre_page', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('Nom_auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Register.auteur')),
            ],
        ),
    ]
