# Generated by Django 5.0.3 on 2024-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0002_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='exemplaires',
            field=models.IntegerField(default=1),
        ),
    ]
