# Generated by Django 5.0.3 on 2024-04-09 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0003_livre_exemplaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_adh', models.IntegerField()),
                ('nom_adh', models.CharField(max_length=50)),
                ('nbrEmprunts_adh', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Register.adherent')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Register.livre')),
            ],
        ),
    ]
