# Generated by Django 5.0.3 on 2024-04-10 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0005_remove_emprunt_date_retour_effective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
