# Generated by Django 5.0.3 on 2024-04-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0006_emprunt_date_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='retard',
            field=models.BooleanField(default=False),
        ),
    ]
