# Generated by Django 5.0.3 on 2024-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0007_emprunt_retard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
