# Generated by Django 5.0.3 on 2024-04-10 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Register', '0008_alter_emprunt_date_emprunt_alter_emprunt_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
